[window]
opacity = 0.7

padding.x = 12
padding.y = 12

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
#size = 9.25

#normal.family = "Maple Mono NF"
#bold.family = "Maple Mono NF"
#italic.family = "Maple Mono NF"
#bold_italic.family = "Maple Mono NF"
normal.family = "Jetbrains Mono Nerd Font"
bold.family = "Jetbrains Mono Nerd Font"
italic.family = "Jetbrains Mono Nerd Font"
bold_italic.family = "Jetbrains Mono Nerd Font"

[colors.primary]
background = "#252525"
foreground = "#edddbd"

[terminal]
# shell = "/bin/fish"
